# PyTorch

### Packages that we will learn:

torch -> Tensors

torch.nn -> Neural Networks

torch.autograd -> Gradients

torch.nn.functional

torch.optim

torch.utils

torchvision -> access to popular datasets, model architecture, and image transofrmations for computer vision

In [57]:
import torch
print(f"torch: {torch.__version__}")

import numpy as np
print(f"numpy: {np.__version__}")

torch: 1.4.0
numpy: 1.18.1


# Tensors 

Each of these examples are specific instances of the more general concept of a tensor:

| Indexes required (Rank)  | Computer science  | Mathematics  | Machine Learning  | 
|:-:|:-:|:-:|:-:|
| 0  | number  | scalar  | (0d-)tensor  |
| 1  | array  | vector  | (1d-)tensor  |
| 2  | 2d-array  | matrix  | (2d-)tensor  |
| n  | nd-array  | nd-tensor  | (nd-)tensor  |

### Example

In [78]:
dd = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

t = torch.tensor(dd)
print(t)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### Tensor Attributes

In [79]:
print(t.shape) # equivalent to size t.size()
# The length of the shape is the rank of our tensor
print(t.numel()) # number of elements

print(len(t.shape))

print(t.dtype)

print(t.device)

print(t.layout) # layout in memory

torch.Size([3, 3])
9
2
torch.int64
cpu
torch.strided


# Tensor operation types

- Reshaping operations
- Element-wise operations
- Reduction operations
- Access operations

## Reshaping Operations

In [ ]:
new_t = t.reshape(1,9)
new_t

Squeezing a tensor removes the dimensions or axes that have a lenght of one:

In [83]:
print(t.reshape(1,9))
print(t.reshape(1,9).shape)

print(t.reshape(1,9).squeeze())
print(t.reshape(1,9).squeeze().shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])


Unsqueezing a tensor adds a dimension with a length of one

In [89]:
print(t.reshape([1,9]).squeeze().unsqueeze(dim=0))
print(t.reshape([1,9]).squeeze().unsqueeze(dim=0).shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])


###### flatten a tensor
Flattening a tensor means to remove all of the dimensions except for me.

In [90]:
print(t.flatten())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


###### concatenating tensors

In [95]:
t1 = torch.tensor([[1,2],[3,4]])
t2 = torch.tensor([[5,6],[7,8]])

print(torch.cat((t1,t2), dim=0))
print(torch.cat((t1,t2), dim=1))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


###### stack tensors

In [109]:
t1 = torch.tensor([[1,1,1,1],
                  [1,1,1,1],
                  [1,1,1,1],
                  [1,1,1,1]])

t2 = torch.tensor([[2,2,2,2],
                  [2,2,2,2],
                  [2,2,2,2],
                  [2,2,2,2]])

t3 = torch.tensor([[3,3,3,3],
                  [3,3,3,3],
                  [3,3,3,3],
                  [3,3,3,3]])

print(t1.shape)
print(t2.shape)
print(t3.shape)

print(torch.stack((t1,t2,t3)).shape)
print(torch.stack((t1,t2,t3)).flatten(start_dim=1).shape)

t_s = torch.stack((t1,t2,t3))
t_s.reshape(3,1,16).squeeze().shape

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([3, 4, 4])
torch.Size([3, 16])


torch.Size([3, 16])

## Element-wise operations

Same shape is requiered (broadcasting has to be possible)

In [113]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [114]:
t1 + t2 

tensor([[ 6,  8],
        [10, 12]])

In [115]:
t1 + 1 # t1.add(1) is the same

tensor([[2, 3],
        [4, 5]])

In [118]:
t1 > 1

tensor([[False,  True],
        [ True,  True]])

In [120]:
t1 == t2

tensor([[False, False],
        [False, False]])

###### TODO: How does Broadcasting work?

## Reduction Operations

In [121]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
])

In [122]:
t.sum()

tensor(24)

In [131]:
t.sum().item()

18

In [125]:
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor([6, 6, 6, 6])
tensor([ 4,  8, 12])


###### argmax

Argmax returns the index location of the maximum value inside a tensor

In [127]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
])

print(t.max())

print(t.argmax()) # index of 5 if flattend 

tensor(5)
tensor(11)


In [129]:
print(t.max(dim=0))
print(t.argmax(dim=0))

torch.return_types.max(
values=tensor([4, 3, 3, 5]),
indices=tensor([2, 1, 1, 2]))
tensor([2, 1, 1, 2])


In [130]:
print(t.max(dim=1))
print(t.argmax(dim=1))

torch.return_types.max(
values=tensor([2, 3, 5]),
indices=tensor([3, 2, 3]))
tensor([3, 2, 3])


# CNNs

typical tensor is of rank 4:

### input Chanel
[B,C,H,W]
- B: batch size
- C: color chanels
- H: image height
- W: image width

# Tensor Creation
### From Existing Data

In [58]:
data = np.array([1,2,3])

#### Constructor

In [59]:
torch.Tensor(data) # copies the Data

tensor([1., 2., 3.])

#### Factory functions

In [60]:
# should be used if you want a copy of the data
torch.tensor(data) # copies the Data

# first choice 

tensor([1, 2, 3])

In [61]:
# should be used if you do not want a copy of the data
torch.as_tensor(data) # shares the Data

# first choice when performance tuning

tensor([1, 2, 3])

In [62]:
torch.from_numpy(data) # shares the Data

tensor([1, 2, 3])

### With predefined functions

In [63]:
torch.eye(2) #identity tensor

tensor([[1., 0.],
        [0., 1.]])

In [66]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [67]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [69]:
torch.rand(2,2)

tensor([[0.4434, 0.3455],
        [0.0160, 0.2224]])